# Generated by Django 5.1.2 on 2024-12-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_user_author_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_id',
            new_name='user',
        ),
    ]
